### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by tieschne** [oakoneric/oakoneric.github.io#1]
Wenn man die oakoneric.github.io Seite mit einem Bildschirm aufruft, der mehr als 1680px in der Breite besitzt, gehen alle Paddings und Margings auf der Seite weg. Ich bin mir nicht sicher ob das Absicht ist, aber die Lesbarkeit und Übersichtlichkeit ist dadurch etwas eingeschänkt. Alles unter 1680px sieht die Seite perfekt wie immer aus :).

![Design](https://user-images.githubusercontent.com/26776282/114316788-5b124d80-9b05-11eb-9bb1-5b1c8211a16e.png)

**Comment by oakoneric** [comment]
Natürlich war das nicht beabsichtigt - sollte jetzt korrigiert sein. :)
